### ISSUE TITLE
 no moov atom Error

### ISSUE THREAD

**Issue by DaGump** [gojibjib/jibjib-query#2]
Error while transforming the MP4 file.

The system returns to me that the MP4 file has no moov atom  Table, but it has.

I tried to add it manually using following command:
`ffmpeg -i flutter_sound_example_1.mp4 -vcodec copy -acodec copy -movflags faststart output_video_file.mp4`
to no avail.

I shortened the audio file.
To no avail.

```
jibjib-api      | 2021/09/09 18:29:08 POST buffer (size: 12243) to http://jibjib-query:8081/detect/binary as application/octet-stream
jibjib-query    | Traceback (most recent call last):
jibjib-query    |   File "/app/code/util/system.py", line 90, in mp4_to_wav
jibjib-query    |     song = AudioSegment.from_file(input_path, "mp4")
jibjib-query    |   File "/usr/local/lib/python2.7/site-packages/pydub/audio_segment.py", line 690, in from_file
jibjib-query    |     raise CouldntDecodeError("Decoding failed. ffmpeg returned error code: {0}\n\nOutput from ffmpeg/avlib:\n\n{1}".format(p.returncode, p_err))
jibjib-query    | CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1
jibjib-query    |
jibjib-query    | Output from ffmpeg/avlib:
jibjib-query    |
jibjib-query    | ffmpeg version 3.2.12-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg developers
jibjib-query    |   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
jibjib-query    |   configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
jibjib-query    |   libavutil      55. 34.101 / 55. 34.101
jibjib-query    |   libavcodec     57. 64.101 / 57. 64.101
jibjib-query    |   libavformat    57. 56.101 / 57. 56.101
jibjib-query    |   libavdevice    57.  1.100 / 57.  1.100
jibjib-query    |   libavfilter     6. 65.100 /  6. 65.100
jibjib-query    |   libavresample   3.  1.  0 /  3.  1.  0
jibjib-query    |   libswscale      4.  2.100 /  4.  2.100
jibjib-query    |   libswresample   2.  3.100 /  2.  3.100
jibjib-query    |   libpostproc    54.  1.100 / 54.  1.100
jibjib-query    | [mov,mp4,m4a,3gp,3g2,mj2 @ 0x564cd092efc0] moov atom not found
jibjib-query    | /app/uploads/238ddacf-20d9-419c-bd69-35305072ca07: Invalid data found when processing input
jibjib-query    |
jibjib-api      | 2021/09/09 18:29:08 84.115.228.34:24032       POST    /detect/binary  185.655391ms

```

**Comment by DaGump** [comment]
my fault. was using Multipart for sending accidentially. Damn you Postman :D
